<?php
session_start();

if (!isset($_SESSION["username"])) {
    header("location:/Clearnce/Login/login.php");
    exit();
}

require_once(__DIR__ . '../libraries/tcpdf/tcpdf.php'); // Include the TCPDF library
require_once('db_connection.php'); // Include your database connection file

$email = $_SESSION["username"]; // Assuming email is stored in session

// Query to fetch username from users table
$query = "SELECT username FROM users WHERE email = ? LIMIT 1";
$stmt = $conn->prepare($query);
$stmt->bind_param('s', $email);
$stmt->execute();
$result = $stmt->get_result();

if ($result->num_rows > 0) {
    $userRow = $result->fetch_assoc();
    $username = $userRow['username'];

    // Query to fetch user data from applyClearance table
    $query = "SELECT * FROM applyClearance WHERE username = ? LIMIT 1";
    $stmt = $conn->prepare($query);
    $stmt->bind_param('s', $username);
    $stmt->execute();
    $result = $stmt->get_result();

    if ($result->num_rows > 0) {
        $row = $result->fetch_assoc();

        // Check if the Final_Stats is "Approve"
        if ($row['Final_Stats'] === 'Approve') {
            // Create new PDF document
            $pdf = new TCPDF();

            // Set document information
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetAuthor('Your Company');
            $pdf->SetTitle('Clearance Approval Letter');
            $pdf->SetSubject('Clearance Approval');

            // Set default header data
            $pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, 'Clearance Approval', 'Generated by Your Company');

            // Set header and footer fonts
            $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
            $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

            // Set default monospaced font
            $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

            // Set margins
            $pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
            $pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
            $pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

            // Set auto page breaks
            $pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

            // Set image scale factor
            $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

            // Add a page
            $pdf->AddPage();

            // Set content for the PDF
            $html = '
                <h1>Clearance Approval Letter</h1>
                <p>Dear ' . htmlspecialchars($row['firstname']) . ',</p>
                <p>We are pleased to inform you that your clearance request has been approved.</p>
                <p>Details:</p>
                <ul>
                    <li>Registration Number: ' . htmlspecialchars($row['regno']) . '</li>
                    <li>Department: ' . htmlspecialchars($row['dept']) . '</li>
                    <li>Academic Year: ' . htmlspecialchars($row['acdemicyr']) . '</li>
                </ul>
                <p>Best regards,</p>
                <p>Your Company</p>
            ';

            // Print text using writeHTML()
            $pdf->writeHTML($html, true, false, true, false, '');

            // Output the PDF
            $pdf->Output('clearance_approval_letter.pdf', 'D');
        } else {
            echo 'Your clearance request has not been approved yet.';
        }
    } else {
        echo 'No clearance request found for this user.';
    }
} else {
    echo 'No user found with this email.';
}

$stmt->close();
$conn->close();
?>
